# Generated by Django 5.1 on 2025-02-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(choices=[('MARUTI', 'Maruti'), ('HYUNDAI', 'Hyundai'), ('TATA', 'Tata'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('FORD', 'Ford'), ('KIA', 'Kia')], max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('Reg_year', models.IntegerField()),
                ('Make_year', models.IntegerField()),
                ('owner', models.IntegerField()),
                ('km_driven', models.IntegerField()),
                ('transmission_type', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('PETROL+CNG', 'Petrol+cng'), ('ELECTRIC', 'Electric')], max_length=20)),
                ('insurance_validity', models.CharField(max_length=100)),
                ('insurance_type', models.CharField(choices=[('COMPREHENSIVE', 'Comprehensive'), ('THIRD-PARTY', 'Third-Party')], max_length=20)),
                ('RTO', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car_location', models.CharField(max_length=100)),
            ],
        ),
    ]
