# Generated by Django 5.1 on 2025-02-08 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='Make_year',
            new_name='manufacture_year',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='Reg_year',
            new_name='registration_year',
        ),
    ]
