# Generated by Django 5.1 on 2025-02-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_make_year_car_manufacture_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='registration_year',
            field=models.DateField(),
        ),
    ]
