# Generated by Django 5.1 on 2025-02-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_car_registration_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOK', 'Book'), ('SOLD', 'Sold')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='registration_year',
            field=models.CharField(help_text='Enter in the format: eg. Aug 2020', max_length=10),
        ),
    ]
