# Generated by Django 5.1 on 2025-02-10 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_car_status_alter_car_registration_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload an image of the car.', upload_to='cars/')),
                ('description', models.CharField(blank=True, help_text='Description of the image (optional).', max_length=255)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.car')),
            ],
        ),
    ]
