# Generated by Django 5.1 on 2025-02-11 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_carimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='registration_month',
            field=models.CharField(choices=[('Jan', 'january'), ('Feb', 'Febuary'), ('March', 'March'), ('April', 'April'), ('May', 'may'), ('June', 'June'), ('July', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], default='january', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Petrol+CNG', 'Petrol+CNG'), ('ELECTRIC', 'Electric')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='insurance_type',
            field=models.CharField(choices=[('Comprehensive', 'Comprehensive'), ('Third-Party', 'Third-Party')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(choices=[('Maruti', 'Maruti'), ('Hyundai', 'Hyundai'), ('Tata', 'Tata'), ('Toyoto', 'Toyota'), ('Honda', 'Honda'), ('Ford', 'Ford'), ('Kia', 'Kia')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='registration_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission_type',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=20),
        ),
    ]
