# Generated by Django 5.1 on 2025-02-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_car_registration_month_alter_car_fuel_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_img',
            field=models.ImageField(default='media\\default_img\\default_img.png', help_text='Upload an image of the car for the display view.', upload_to='title_car/'),
        ),
    ]
